version: "3"
services:
  app:
    env_file:
      - .env
    image: usta-backend
    container_name: usta-backend
    #network_mode: host
    restart: always
    build: .
    environment:
      - TZ=UTC
    ports:
      - "127.0.0.1:3000:3000"
